In [1]:
import pandas as pd
import numpy as np
import joblib

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

In [2]:
df = pd.read_csv("cicids2017_sample.csv")

df.head()

,Destination Port,Flow Duration,Total Fwd Packets,Total Length of Fwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,Bwd Packet Length Min,...,Init_Win_bytes_backward,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Max,Active Min,Idle Mean,Idle Max,Idle Min,Attack Type
0,443,58244816,13,838,357,0,64.461538,116.496506,1448,0,...,972,6,32,177029.0,177029,177029,58100000.0,58100000,58100000,Normal Traffic
1,53,424,1,49,49,49,49.000000,0.000000,77,77,...,-1,0,32,0.0,0,0,0.0,0,0,Normal Traffic
2,443,5826402,7,635,517,0,90.714286,190.707205,150,0,...,122,3,32,555380.0,555380,555380,5271005.0,5271005,5271005,Normal Traffic
3,53,30417,4,120,30,30,30.000000,0.000000,207,207,...,-1,3,20,0.0,0,0,0.0,0,0,Normal Traffic
4,53,30708,2,68,34,34,34.000000,0.000000,114,114,...,-1,1,20,0.0,0,0,0.0,0,0,Normal Traffic

In [4]:
X = df.drop("Attack Type", axis=1)

y = df["Attack Type"]

scaler = StandardScaler()

X = scaler.fit_transform(X)

joblib.dump(scaler,"models/scaler.pkl")

['models/scaler.pkl']

In [13]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

y = label_encoder.fit_transform(df["Attack Type"])

joblib.dump(label_encoder, "models/label_encoder.pkl")

['models/label_encoder.pkl']

In [14]:
X_train,X_test,y_train,y_test=train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print(X_train.shape)

print(X_test.shape)

(400000, 52)
(100000, 52)

Logistic Regression

In [18]:
logistic = LogisticRegression(max_iter=1000)

logistic.fit(X_train,y_train)

y_pred_log = logistic.predict(X_test)

print("Accuracy :",accuracy_score(y_test,y_pred_log))

print(classification_report(y_test,y_pred_log))

joblib.dump(logistic,"models/logistic_regression.pkl")

Accuracy : 0.97516
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        77
           1       1.00      0.78      0.87       363
           2       0.99      0.96      0.98      5078
           3       0.99      0.93      0.95      7686
           4       0.99      0.98      0.99     83113
           5       0.73      0.99      0.84      3598
           6       0.00      0.00      0.00        85

    accuracy                           0.98    100000
   macro avg       0.67      0.66      0.66    100000
weighted avg       0.98      0.98      0.98    100000

c:\Users\Lenovo\AppData\Local\Python\pythoncore-3.13-64\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Lenovo\AppData\Local\Python\pythoncore-3.13-64\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Lenovo\AppData\Local\Python\pythoncore-3.13-64\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

['models/logistic_regression.pkl']

Decision Tree

In [19]:
decision_tree = DecisionTreeClassifier(random_state=42)

decision_tree.fit(X_train,y_train)

y_pred_dt = decision_tree.predict(X_test)

print("Accuracy :",accuracy_score(y_test,y_pred_dt))

print(classification_report(y_test,y_pred_dt))

joblib.dump(decision_tree,"models/decision_tree.pkl")

Accuracy : 0.99838
              precision    recall  f1-score   support

           0       0.81      0.81      0.81        77
           1       1.00      0.99      1.00       363
           2       1.00      1.00      1.00      5078
           3       1.00      1.00      1.00      7686
           4       1.00      1.00      1.00     83113
           5       0.99      0.99      0.99      3598
           6       0.96      0.93      0.95        85

    accuracy                           1.00    100000
   macro avg       0.96      0.96      0.96    100000
weighted avg       1.00      1.00      1.00    100000

['models/decision_tree.pkl']

Random Forest

In [20]:
random_forest = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

random_forest.fit(X_train,y_train)

y_pred_rf=random_forest.predict(X_test)

print("Accuracy :",accuracy_score(y_test,y_pred_rf))

print(classification_report(y_test,y_pred_rf))

joblib.dump(random_forest,"models/random_forest.pkl")

Accuracy : 0.99865
              precision    recall  f1-score   support

           0       0.77      0.60      0.67        77
           1       1.00      0.99      1.00       363
           2       1.00      1.00      1.00      5078
           3       1.00      1.00      1.00      7686
           4       1.00      1.00      1.00     83113
           5       0.99      1.00      0.99      3598
           6       0.98      0.94      0.96        85

    accuracy                           1.00    100000
   macro avg       0.96      0.93      0.95    100000
weighted avg       1.00      1.00      1.00    100000

['models/random_forest.pkl']

XGBoost

In [15]:
xgboost = XGBClassifier(
    objective="multi:softmax",
    eval_metric="mlogloss",
    random_state=42
)

xgboost.fit(X_train,y_train)

y_pred_xgb=xgboost.predict(X_test)

print("Accuracy :",accuracy_score(y_test,y_pred_xgb))

print(classification_report(y_test,y_pred_xgb))

joblib.dump(xgboost,"models/xgboost.pkl")

Accuracy : 0.99901
              precision    recall  f1-score   support

           0       0.82      0.83      0.83        77
           1       1.00      1.00      1.00       363
           2       1.00      1.00      1.00      5078
           3       1.00      1.00      1.00      7686
           4       1.00      1.00      1.00     83113
           5       0.99      1.00      0.99      3598
           6       0.96      0.94      0.95        85

    accuracy                           1.00    100000
   macro avg       0.97      0.97      0.97    100000
weighted avg       1.00      1.00      1.00    100000

['models/xgboost.pkl']

In [16]:
joblib.dump(
    xgboost,
    "models/network_intrusion_detector.pkl"
)

['models/network_intrusion_detector.pkl']

In [21]:
results = {

    "Model":[
        "Logistic Regression",
        "Decision Tree",
        "Random Forest",
        "XGBoost"
    ],

    "Accuracy":[

        accuracy_score(y_test,y_pred_log),

        accuracy_score(y_test,y_pred_dt),

        accuracy_score(y_test,y_pred_rf),

        accuracy_score(y_test,y_pred_xgb)
    ],

    "Precision":[

        precision_score(y_test,y_pred_log,average="weighted"),

        precision_score(y_test,y_pred_dt,average="weighted"),

        precision_score(y_test,y_pred_rf,average="weighted"),

        precision_score(y_test,y_pred_xgb,average="weighted")
    ],

    "Recall":[

        recall_score(y_test,y_pred_log,average="weighted"),

        recall_score(y_test,y_pred_dt,average="weighted"),

        recall_score(y_test,y_pred_rf,average="weighted"),

        recall_score(y_test,y_pred_xgb,average="weighted")
    ],

    "F1 Score":[

        f1_score(y_test,y_pred_log,average="weighted"),

        f1_score(y_test,y_pred_dt,average="weighted"),

        f1_score(y_test,y_pred_rf,average="weighted"),

        f1_score(y_test,y_pred_xgb,average="weighted")
    ]

}

comparison = pd.DataFrame(results)

comparison

c:\Users\Lenovo\AppData\Local\Python\pythoncore-3.13-64\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

                 Model  Accuracy  Precision   Recall  F1 Score
0  Logistic Regression   0.97516   0.977034  0.97516  0.975206
1        Decision Tree   0.99838   0.998378  0.99838  0.998379
2        Random Forest   0.99865   0.998613  0.99865  0.998622
3              XGBoost   0.99901   0.999014  0.99901  0.999011